package com.jiyun.com.day07_greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jiyun.pandatv.moudle.db.History;
import com.jiyun.com.day07_greendao.VideoCollectBean;

import com.jiyun.com.day07_greendao.HistoryDao;
import com.jiyun.com.day07_greendao.VideoCollectBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig historyDaoConfig;
    private final DaoConfig videoCollectBeanDaoConfig;

    private final HistoryDao historyDao;
    private final VideoCollectBeanDao videoCollectBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        videoCollectBeanDaoConfig = daoConfigMap.get(VideoCollectBeanDao.class).clone();
        videoCollectBeanDaoConfig.initIdentityScope(type);

        historyDao = new HistoryDao(historyDaoConfig, this);
        videoCollectBeanDao = new VideoCollectBeanDao(videoCollectBeanDaoConfig, this);

        registerDao(History.class, historyDao);
        registerDao(VideoCollectBean.class, videoCollectBeanDao);
    }
    
    public void clear() {
        historyDaoConfig.clearIdentityScope();
        videoCollectBeanDaoConfig.clearIdentityScope();
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

    public VideoCollectBeanDao getVideoCollectBeanDao() {
        return videoCollectBeanDao;
    }

}
