package com.jiyun.com.day07_greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jiyun.com.day07_greendao.VideoCollectBean;
import com.jiyun.pandatv.moudle.db.History;

import com.jiyun.com.day07_greendao.VideoCollectBeanDao;
import com.jiyun.com.day07_greendao.HistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig videoCollectBeanDaoConfig;
    private final DaoConfig historyDaoConfig;

    private final VideoCollectBeanDao videoCollectBeanDao;
    private final HistoryDao historyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        videoCollectBeanDaoConfig = daoConfigMap.get(VideoCollectBeanDao.class).clone();
        videoCollectBeanDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        videoCollectBeanDao = new VideoCollectBeanDao(videoCollectBeanDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);

        registerDao(VideoCollectBean.class, videoCollectBeanDao);
        registerDao(History.class, historyDao);
    }
    
    public void clear() {
        videoCollectBeanDaoConfig.clearIdentityScope();
        historyDaoConfig.clearIdentityScope();
    }

    public VideoCollectBeanDao getVideoCollectBeanDao() {
        return videoCollectBeanDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

}
